name: "[Server] Deploy"

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          # Mostly to avoid GitHub rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Install Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "[Server] Build Container Image"
        run: |
          nix build .#dockerImage

      - name: "[Heroku] Update container image"
        run: |
          just update-registry-ci

      - name: "[Heroku] Create Release"
        run: |
          just heroku-release-ci
