name: Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  PGHOST: localhost
  PGPORT: 5432
  PGPASSWORD: admin
  PGUSER: admin
  PGDATABASE: mmo

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
          POSTGRES_USER: ${{ env.PGUSER }}
          POSTGRES_DATABASE: ${{ env.PGDATABASE }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          # Mostly to avoid GitHub rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Install Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "[Erlang] Postgres migrations"
        run: |
          #nix develop .#ci --impure -c just build
          echo "todo"

      - name: "[Erlang] build"
        run: |
          nix develop .#ci --impure -c just build

      - name: "[Erlang] tests"
        run: |
          nix develop .#ci --impure -c just test

# Uncomment this trash when you fix the zig code
#      - name: "[Zig] build"
#        run: |
#          nix develop .#ci --impure -c just client
#
#      - name: "[Zig] tests"
#        run: |
#          nix develop .#ci --impure -c just client-test
